version: '3.7'

services:
  snkpoint-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/snkpoint/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    environment:
      - TZ=Asia/Seoul

  snkpoint-database:
    platform: linux/x86_64
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'snkpoint'
      MYSQL_ROOT_PASSWORD: 'root'
      TZ: Asia/Seoul
    ports:
      # For Deploy On VM Instance
      - 1328:3306
      # For Dev On Localhost
      # - 3306:3306

  # Redis
  snkpoint-redis:
    image: redis:latest
    ports:
      - 6379:6379
